import { dirname, relative } from 'pathe';

import { hasProjectConfig } from '#src/config/effective.ts';
import { LayerscopeError } from '#src/errors.ts';
import type { AnalyzeResult, Finding } from '#src/types.ts';
import { compareStrings, plural } from '#src/utils/strings.ts';

/** A dependency between two layers that exists today. */
export interface AllowedEdge {
  from: string;
  to: string;
  count: number;
  /** First reference as `file:line`, relative to the root. */
  example: string;
}

export interface Cluster {
  key: string;
  count: number;
}

export interface Readiness {
  references: number;
  unresolved: number;
  byLayer: Cluster[];
  byDirectory: Cluster[];
}

export interface Proposal {
  edges: AllowedEdge[];
  readiness: Readiness;
  /** Findings a baseline would have to accept once the config is in place. */
  remaining: Finding[];
}

// ponytail: top 5 only; make it a flag if the long tail matters.
const CLUSTER_LIMIT = 5;

function collectEdges(result: AnalyzeResult): AllowedEdge[] {
  const edges = new Map<string, AllowedEdge>();
  for (const { file, line, fromLayer, toLayer } of result.edges) {
    if (toLayer === null || toLayer === fromLayer) {
      continue;
    }
    const key = `${fromLayer}\0${toLayer}`;
    const edge = edges.get(key);
    if (edge === undefined) {
      const example = `${relative(result.rootDir, file)}:${line}`;
      edges.set(key, { from: fromLayer, to: toLayer, count: 1, example });
    } else {
      edge.count += 1;
    }
  }
  return [...edges.values()].toSorted(
    (a, b) => compareStrings(a.from, b.from) || compareStrings(a.to, b.to),
  );
}

function topClusters(keys: string[]): Cluster[] {
  const counts = new Map<string, number>();
  for (const key of keys) {
    counts.set(key, (counts.get(key) ?? 0) + 1);
  }
  return [...counts]
    .map(([key, count]) => ({ key, count }))
    .toSorted((a, b) => b.count - a.count || compareStrings(a.key, b.key))
    .slice(0, CLUSTER_LIMIT);
}

function measureReadiness(result: AnalyzeResult): Readiness {
  const unresolved = result.findings.filter(finding => finding.rule === 'unresolved-reference');
  return {
    references: result.edges.length + unresolved.length,
    unresolved: unresolved.length,
    byLayer: topClusters(unresolved.map(finding => finding.fromLayer)),
    byDirectory: topClusters(
      unresolved.map(finding => dirname(relative(result.rootDir, finding.file))),
    ),
  };
}

/** Layers in both places is an error at check time, so don't create the second one. */
export function assertNoNuxtConfigLayers(result: AnalyzeResult, hasConfigFile: boolean): void {
  if (!hasConfigFile && hasProjectConfig(result.config)) {
    throw new LayerscopeError(
      'Layers or rules are already set in the "layerscope" key of nuxt.config. Move them to layerscope.config.ts, or remove the key and run init again.',
    );
  }
}

/**
 * Expects a result analyzed without an `allow` map, so every layer is unrestricted and the edges
 * are exactly the dependencies that exist.
 */
export function propose(result: AnalyzeResult): Proposal {
  return {
    edges: collectEdges(result),
    readiness: measureReadiness(result),
    remaining: result.findings,
  };
}

function quote(text: string): string {
  return `'${text.replaceAll('\\', '\\\\').replaceAll("'", String.raw`\'`)}'`;
}

function property(name: string): string {
  return /^[A-Za-z_$][\w$]*$/u.test(name) ? name : quote(name);
}

export function renderConfig(layers: string[], edges: AllowedEdge[]): string {
  const lines = [
    "import { defineConfig } from 'nuxt-layerscope';",
    '',
    '// Generated by `layerscope init` from the dependencies that exist today.',
    '// Delete a line to forbid that dependency, then run `layerscope check`.',
    'export default defineConfig({',
    '  layers: {',
  ];
  for (const layer of layers) {
    const allowed = edges.filter(edge => edge.from === layer);
    if (allowed.length === 0) {
      lines.push(`    ${property(layer)}: { allow: [] },`);
      continue;
    }
    lines.push(`    ${property(layer)}: {`, '      allow: [');
    for (const edge of allowed) {
      lines.push(
        `        ${quote(edge.to)}, // ${plural(edge.count, 'reference')}, e.g. ${edge.example}`,
      );
    }
    lines.push('      ],', '    },');
  }
  lines.push('  },', '});', '');
  return lines.join('\n');
}
