import { plural } from '#src/utils/strings.ts';

import type { AllowedEdge } from './types.ts';

function quote(text: string): string {
  return `'${text.replaceAll('\\', '\\\\').replaceAll("'", String.raw`\'`)}'`;
}

function property(name: string): string {
  return /^[A-Za-z_$][\w$]*$/u.test(name) ? name : quote(name);
}

function layerLines(layer: string, edges: AllowedEdge[]): string[] {
  if (edges.length === 0) {
    return [`    ${property(layer)}: { allow: [] },`];
  }
  return [
    `    ${property(layer)}: {`,
    '      allow: [',
    ...edges.map(
      edge =>
        `        ${quote(edge.to)}, // ${plural(edge.count, 'reference')}, e.g. ${edge.example}`,
    ),
    '      ],',
    '    },',
  ];
}

export function renderConfig(layers: string[], edges: AllowedEdge[]): string {
  return [
    "import { defineConfig } from 'nuxt-layerscope';",
    '',
    '// Generated by `layerscope init`. Delete a line to forbid that dependency.',
    'export default defineConfig({',
    '  layers: {',
    ...layers.flatMap(layer =>
      layerLines(
        layer,
        edges.filter(edge => edge.from === layer),
      ),
    ),
    '  },',
    '});',
    '',
  ].join('\n');
}
