version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      actions:
        patterns: ['*']

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    exclude-paths:
      - packages/layerscope/test/fixtures/**
    groups:
      minor-and-patch:
        update-types: [minor, patch]
